### ISSUE TITLE
Lack of user consent for automatic download

### ISSUE THREAD

**Issue by imbev** [nodetool-ai/nodetool#11]
Upon starting the application, nodetool begins a 4GB download without warning the user.

The user should be informed of the size of the environment and have the opportunity to accept/deny the download beforehand.

**Comment by georgi** [comment]
Agreed. I think we will add a dialog to select the install path and inform about the required disk usage.

**Comment by georgi** [comment]
addressed in 00e8bfb5

**Comment by heavy-d** [comment]
thanks for reporting @imbev 
will be in upcoming release
