### ISSUE TITLE
Conda Environment is located under ~/.config

### ISSUE THREAD

**Issue by imbev** [nodetool-ai/nodetool#12]
nodetool currently prepares a Python environment under `~/.config/nodetool-electron/conda_env`.

This is a problem because `~/.config` is intended for per-user configuration, not application data. Following the XDG Base Directory standard, this environment should be located within the XDG_DATA_HOME directory instead, somewhere under `~/.local/share` .

**Comment by georgi** [comment]
Good point. Do you think it's better to allow the user to select the location?

**Comment by imbev** [comment]
Yes, with a provided default

**Comment by georgi** [comment]
addressed in commit 00e8bfb5

**Comment by heavy-d** [comment]
thanks @imbev 
will be in upcoming release
